# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# Node.js (Vite) - Build once, deploy artifact to Dev/Test/Prod via Environments

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: Variables

stages:
# -------------------------
# 1) BUILD STAGE
# -------------------------
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - script: |
        set -e

        BASE_VERSION=$(node -p "require('./package.json').version")
        MAJOR_MINOR=$(echo $BASE_VERSION | cut -d. -f1,2)
        PATCH=$(Build.BuildId)

        FULL_VERSION="$MAJOR_MINOR.$PATCH"
        SHORT_SHA=$(echo "$(Build.SourceVersion)" | cut -c1-7)

        echo "FULL_VERSION=$FULL_VERSION"

        npm ci
        VITE_APP_VERSION="$FULL_VERSION" \
        VITE_BUILD_ID="$(Build.BuildNumber)" \
        VITE_GIT_SHA="$SHORT_SHA" \
        npm run build
      displayName: 'Build with dynamic patch version'

    - task: ArchiveFiles@2
      displayName: 'Archive dist'
      inputs:
        rootFolderOrFile: 'dist'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/dist.zip'
        replaceExistingArchive: true

    - task: PublishPipelineArtifact@1
      displayName: 'Publish dist.zip as artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/dist.zip'
        artifact: 'drop'
        publishLocation: 'pipeline'

- template: pipelines/deploy-swa.yml
  parameters:
    stageName: DeployDev
    environmentName: dev
    tokenVariable: SWA_DEPLOYMENT_TOKEN

- template: pipelines/deploy-swa.yml
  parameters:
    stageName: DeployTest
    environmentName: test
    tokenVariable: SWA_DEPLOYMENT_TOKEN_TEST

- template: pipelines/deploy-swa.yml
  parameters:
    stageName: DeployProd
    environmentName: production
    tokenVariable: SWA_DEPLOYMENT_TOKEN_PROD